### ISSUE TITLE
Wrong order of decimals

### ISSUE THREAD

**Issue by kos59125** [kos59125/naturalsort#5]
``` R
> naturalorder(c("1.001", "1.002", "1.010", "1.02", "1.1", "1.3"))
[1] 1 5 2 4 6 3
```

should be

``` R
[1] 1 2 3 4 5 6
```

**Comment by sepuku** [comment]
This is still happening on naturalsort by the way... Please see open issue: https://github.com/kos59125/naturalsort/issues/9

Thanks!
