### ISSUE TITLE
Feature Request:  naturalfactor

### ISSUE THREAD

**Issue by billdenney** [kos59125/naturalsort#6]
Thanks for the very useful package!

I find a common use of the package is to make factors that are sorted in order.  Could you add the following function or similar to the package simplifying making factors?

```
naturalfactor <- function(text, ...)
  factor(x=text, levels=naturalsort(unique(text), ...), ordered=TRUE)
```

**Comment by kos59125** [comment]
Good news:
I have added the function and submitted to CRAN.
Wait for publish.
